title = "hugo testing"
baseURL = "https://chreliot.github.io/hugo-testing/"
languageCode = 'en-us'
title = '@@TITLE@@'

[module]

[[module.imports]]
  path = 'github.com/yihui/hugo-xmin'
  disable=false
